server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.85
spring:
  cloud:
    config:
      import-check:
        enabled: false