server:
  port: 8083
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

spring:
  application:
    name: staffing-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/staffing_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibaseChangeLog.xml

logging:
  charset:
    console: UTF-8